openapi: 3.0.3
info:
  title: Facebot API Suite
  version: 1.0.0
  description: |
    API for activating/deactivating Facebots and retrieving reports

paths:
  /facebots/activate:
    post:
      summary: Activate a Facebot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - fb_config_params
              properties:
                user_id:
                  type: string
                  description: Unique identifier for the user
                fb_config_params:
                  type: object
                  properties:
                    facebot_name:
                      type: string
                      default: ""
                    avatar_id:
                      type: string
                      default: ""
                    contact_prompt_point:
                      type: integer
                      default: 0
                    facebot_title:
                      type: string
                      default: "AI assistant 24/7"
                    auto_open:
                      type: boolean
                      default: false
                    active:
                      type: boolean
                      default: true
                    theme_color:
                      type: string
                      default: "#034b83"
                    contact_fields:
                      type: object
                    tooltip_text:
                      type: string
                      default: ""
                    tooltip_text_colour:
                      type: string
                      default: ""
                    notification_email_id:
                      type: string
                      default: ""
                    audio_input:
                      type: boolean
                      default: true
                    widget_placement:
                      type: string
                      enum: [left, right]
                      default: "right"
      responses:
        "200":
          description: Facebot activated successfully
        "400":
          description: Invalid input

  /facebots/deactivate:
    post:
      summary: Deactivate a Facebot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
              properties:
                user_id:
                  type: string
                  description: Unique identifier for the user
      responses:
        "200":
          description: Facebot deactivated successfully
        "400":
          description: Invalid input

  /facebots/reports/intent:
    get:
      summary: Get intent report data for a user
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: from_date
          in: query
          required: true
          description: Start date in YYYY-MM-DD format
          schema:
            type: string
            format: date
        - name: to_date
          in: query
          required: true
          description: End date in YYYY-MM-DD format
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Successful response with report data
          content:
            application/json:
              schema:
                type: object
                properties:
                  top_last_questions:
                    type: array
                    description: Questions asked as the last question in a conversation
                    items:
                      $ref: "#/components/schemas/QuestionStat"
                  top_questions:
                    type: array
                    description: Most frequently asked questions overall
                    items:
                      $ref: "#/components/schemas/QuestionStat"
                  fallback_questions:
                    type: array
                    description: Questions that triggered a fallback response
                    items:
                      $ref: "#/components/schemas/QuestionStat"
        "400":
          description: Invalid parameters
        "500":
            description: Server error

  /facebots/reports/engagement:
    get:
      summary: Get engagement metrics for a user
      description: Returns engagement data like visitor counts, session counts, top cities, and daily breakdowns over a specified date range.
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
        - name: from_date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to_date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Successful response with engagement metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_visitors:
                    type: integer
                    description: Total number of visitors
                  total_sessions:
                    type: integer
                    description: Total number of sessions
                  visitors_per_date:
                    type: array
                    description: List of visitors count per day
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          description: The date of the visit
                        visitors:
                          type: integer
                          description: Number of visitors on that date
                  sessions_per_date:
                    type: array
                    description: List of session count per day
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                          format: date
                          description: The date of the session
                        sessions:
                          type: integer
                          description: Number of sessions on that date
                  top_cities:
                    type: array
                    description: Top 5 cities with the most visitors
                    items:
                      type: object
                      properties:
                        city:
                          type: string
                        visitors:
                          type: integer
        "400":
          description: Invalid parameters
        "500":
          description: Server error

components:
  schemas:
    QuestionStat:
      type: object
      properties:
        facebot_id:
          type: string
        date:
          type: string
          format: date
        question:
          type: string
        count:
          type: integer
